name: vendor
description: Vendor app for Enclave

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+9
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.0.8
  provider: ^3.1.0+1
  google_sign_in: ^4.0.13
  curved_navigation_bar: ^0.3.1
  carousel_slider: ^1.3.1
  intl: ^0.16.0
  flutter_picker: ^1.1.0
  photo_view: ^0.8.0
  multi_image_picker: ^4.6.1
  flutter_image_compress: ^0.6.3
  permission_handler: ^4.0.0
  path_provider: ^1.5.1
  square_in_app_payments: ^1.3.0
  cloud_functions: ^0.4.1+6
  connectivity: ^0.4.6+1
  url_launcher: ^5.4.1
  google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  rxdart: ^0.23.1
  badges: ^1.1.0
  flutter_statusbarcolor: ^0.2.3
  flutter_datetime_picker: ^1.3.1
  flutter_advanced_networkimage: ^0.6.2
  firebase_messaging: ^6.0.9
  flutter_credit_card: ^0.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google-logo.png
    - assets/images/instagram.png
    - assets/images/loading.gif
    - assets/images/loading-dots.gif
    - assets/images/user.png
    - assets/images/team/amos.png
    - assets/images/team/prince.png
    - assets/images/team/sedem.png
    - assets/images/cards/airtel-logo.png
    - assets/images/cards/airtel-logo-2.png
    - assets/images/cards/vodafone-logo.png
    - assets/images/cards/vodafone-logo-2.png
    - assets/images/cards/mtn-logo.png
    - assets/images/cards/tigo-logo.png
    - assets/images/cards/emv.png

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
