/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData reading = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData event_ads = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData event_calender = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData building = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData add_credit_card = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData reset_padlock = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData security = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData transaction = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData gallery = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData file_1 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData parking = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData ring = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData credit_cards_payment = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData insta = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData twitter_filled = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData checked = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData parking_car = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData toilet = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData toilet_wc = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData dimension = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData audience = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData enterprise = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData location_sleek = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData house_location = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData verified = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData cancel_search = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData sim = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData sim_card = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData atm_card = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData chip = const IconData(0xe82a, fontFamily: _kFontFam);
}
